### ISSUE TITLE
Current release vs. codebase?

### ISSUE THREAD

**Issue by tobiasbp** [metalmatze/digitalocean_exporter#10]
The current release is 0.5 and is from 2018. The exporter seems to have been updated since. Is a new release with the changes scheduled?

**Comment by metalmatze** [comment]
There has been some development, but also not too much :)
https://github.com/metalmatze/digitalocean_exporter/compare/0.5...master

Let me cut a 0.6.0 now.

**Comment by metalmatze** [comment]
There you go! https://github.com/metalmatze/digitalocean_exporter/releases/tag/0.6.0 
Also on Docker Hub as container image.
