### ISSUE TITLE
Droplet List is limited to 20 droplets

### ISSUE THREAD

**Issue by alexandermarston** [metalmatze/digitalocean_exporter#11]
It would appear that the Droplet collector is only returning 20 results as the API endpoint is paginated - can this be looked into?

**Comment by metalmatze** [comment]
That should be an issue for what was started in #2 
It seems that the PR was closed as I was too unresponsive... :confused: 
Maybe we can still use that one even if it was closed.

**Comment by alexandermarston** [comment]
> That should be an issue for what was started in #2
> It seems that the PR was closed as I was too unresponsive... 😕
> Maybe we can still use that one even if it was closed.

I'm happy to test this on an environment with 50-odd droplets if you can arrange a test release?

**Comment by metalmatze** [comment]
Could you build the project yourself for the test case? Essentially cloning and then running `make build` should be enough.

**Comment by alexandermarston** [comment]
#12 raised. I have tested this and it works as expected.

**Comment by alexandermarston** [comment]
Resolved by #12
