### ISSUE TITLE
Feature Request: Add digitalocean apps/app deployments to exporter

### ISSUE THREAD

**Issue by circa10a** [metalmatze/digitalocean_exporter#15]
Digitalocean added [their new apps platform](https://www.digitalocean.com/products/app-platform/) which is also accessible through [godo](https://godoc.org/github.com/digitalocean/godo#App). Would be useful to have things like apps and deployments to be exported.

**Comment by metalmatze** [comment]
Great idea!
I've only played with Apps in their UI, haven't looked at the API for this. 
Is there enough to making something useful with? 
Happy to accept features to add this :)

**Comment by circa10a** [comment]
Absolutely. I think the biggest value add here is deployment statuses. Having live updating dashboards of app deployments would be pretty cool :)

Another use case is if folks use the app platform for review apps(e.g. deploy as part PR pipline), this could help keep track of trends to monitor costs.

There's actually a [hackathon occurring right now](https://dev.to/devteam/announcing-the-digitalocean-app-platform-hackathon-on-dev-2i1k) that emphasizes utilizing the app platform. Maybe having these additions and deploying the exporter would be a good submission!

**Comment by metalmatze** [comment]
Cool! Yes, sound good.
Feel free to add the feature and submit it. 
I'm mostly done for this year and looking forward to getting some rest, so don't expect me to add this myself, but I'd be happy to review and help if need be.
